services:
  api:
    build: .
    container_name: api_dev
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    networks:
      - home-network

networks:
  home-network:
    external: true

